PercivalBpmEstimator: push float literal instead of double
fix error due to missing conversion from double to Real. gcc 10.2.0
RuntimeError: In PercivalBpmEstimator.compute: While trying to push item into source PercivalBpmEstimator::bpm:
Error when checking types. Expected: Real, received: double